import XCTest
@testable import DrivePeakKit

final class StubParserTests: XCTestCase {

    // The exact JSON shape verified from a real .gdoc on disk.
    private let realStub = Data("""
    {"":"WARNING! DO NOT EDIT THIS FILE! ANY CHANGES MADE WILL BE LOST!",\
    "doc_id":"1Ypz5VJ4eL_G2T5CJsXjYOU_4HBuF4J0gn0r-dACtmcc",\
    "resource_key":"","email":"me@example.com"}
    """.utf8)

    func testParsesRealStub() throws {
        let stub = try StubParser.parse(data: realStub, type: .doc, title: "My Doc")
        XCTAssertEqual(stub.type, .doc)
        XCTAssertEqual(stub.title, "My Doc")
        XCTAssertEqual(stub.docID, "1Ypz5VJ4eL_G2T5CJsXjYOU_4HBuF4J0gn0r-dACtmcc")
        XCTAssertNil(stub.resourceKey)          // empty string → nil
        XCTAssertEqual(stub.ownerEmail, "me@example.com")
    }

    func testResourceKeyKeptWhenPresent() throws {
        let data = Data(#"{"doc_id":"abc","resource_key":"rk123"}"#.utf8)
        let stub = try StubParser.parse(data: data, type: .sheet, title: "S")
        XCTAssertEqual(stub.resourceKey, "rk123")
    }

    func testMissingDocIDThrows() {
        let data = Data(#"{"resource_key":"","email":"x@y.com"}"#.utf8)
        XCTAssertThrowsError(try StubParser.parse(data: data, type: .doc, title: "T")) {
            XCTAssertEqual($0 as? StubParseError, .missingDocID)
        }
    }

    func testEmptyDocIDThrows() {
        let data = Data(#"{"doc_id":"   "}"#.utf8)
        XCTAssertThrowsError(try StubParser.parse(data: data, type: .doc, title: "T")) {
            XCTAssertEqual($0 as? StubParseError, .missingDocID)
        }
    }

    func testNonJSONThrows() {
        let data = Data("not json at all".utf8)
        XCTAssertThrowsError(try StubParser.parse(data: data, type: .doc, title: "T")) {
            XCTAssertEqual($0 as? StubParseError, .notJSON)
        }
    }

    func testParseFileUnsupportedExtension() {
        let url = URL(fileURLWithPath: "/tmp/whatever.pdf")
        XCTAssertThrowsError(try StubParser.parse(fileAt: url)) {
            XCTAssertEqual($0 as? StubParseError, .unsupportedType("pdf"))
        }
    }
}

final class GoogleURLBuilderTests: XCTestCase {

    func testDocURL() {
        let stub = Stub(type: .doc, title: "T", docID: "ID1")
        XCTAssertEqual(GoogleURLBuilder.openURL(for: stub)?.absoluteString,
                       "https://docs.google.com/document/d/ID1/edit")
    }

    func testAllTypesProduceValidURLWithCorrectPath() {
        let expectedPath: [WorkspaceType: String] = [
            .doc: "document/d", .sheet: "spreadsheets/d", .slides: "presentation/d",
            .drawing: "drawings/d", .form: "forms/d", .site: "sites/d",
        ]
        for type in WorkspaceType.allCases {
            let stub = Stub(type: type, title: "T", docID: "XYZ")
            let url = GoogleURLBuilder.openURL(for: stub)
            XCTAssertNotNil(url, "\(type) produced nil URL")
            XCTAssertTrue(url!.absoluteString.contains("/\(expectedPath[type]!)/XYZ/edit"),
                          "\(type) → \(url!.absoluteString)")
        }
    }

    func testSiteUsesSitesHost() {
        let stub = Stub(type: .site, title: "T", docID: "ID")
        XCTAssertEqual(GoogleURLBuilder.openURL(for: stub)?.host, "sites.google.com")
    }

    func testResourceKeyBecomesQuery() {
        let stub = Stub(type: .doc, title: "T", docID: "ID", resourceKey: "RK")
        let s = GoogleURLBuilder.openURL(for: stub)!.absoluteString
        XCTAssertTrue(s.contains("resourcekey=RK"), s)
    }
}
